version: '3'
services:
  database_tsauth:
    image: postgres:13.1-alpine
    container_name: database_tsauth
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
